### PR TITLE
Iterable double stream java goodie

### PR DESCRIPTION
**Pull request by utsavatwork**

### CODE REVIEW

**Comment by utsavatwork** [comment]
Addresses the ticket https://github.com/code-chronicles-code/leetcode-curriculum/issues/183

**Comment by miorel** [comment]
Hey @utsavatwork, this is looking good! There are a couple of minor changes needed to get this mergeable:

* It looks like there is some minor whitespace formatting issue in the files you created. If you have installed any dependencies by running `yarn` then you will be able to run `yarn format` in the `adventure-pack` workspace to fix this.
* We have some snapshot tests that assert that each goody can be successfully rendered. Since you added new goodies, there will be new snapshots. You can regenerate these by running `yarn package-goodies:test -u` (for update) in the `adventure-pack` workspace.
* You are welcome to add your name to the list of authors/contributors -- there is an `AUTHORS` file at the top-level of the repository and a "contributors" field in the `adventure-pack` workspace `package.json` file.

After these changes, I think this PR can be merged. Thanks!

**Comment by utsavatwork** [comment]
> Hey @utsavatwork, this is looking good! There are a couple of minor changes needed to get this mergeable:
> 
> * It looks like there is some minor whitespace formatting issue in the files you created. If you have installed any dependencies by running `yarn` then you will be able to run `yarn format` in the `adventure-pack` workspace to fix this.
> * We have some snapshot tests that assert that each goody can be successfully rendered. Since you added new goodies, there will be new snapshots. You can regenerate these by running `yarn package-goodies:test -u` (for update) in the `adventure-pack` workspace.
> * You are welcome to add your name to the list of authors/contributors -- there is an `AUTHORS` file at the top-level of the repository and a "contributors" field in the `adventure-pack` workspace `package.json` file.
> 
> After these changes, I think this PR can be merged. Thanks!

Ok. I have made the changes as you said @miorel. I hope it'll all work now.

**Review by miorel — APPROVED** [review]

**Comment by miorel** [comment]
Thanks for the PR! You can now see the `IterableDoubleStream` at https://code-chronicles-code.github.io/leetcode-curriculum/
(The UI hasn't been a priority recently 😅)

If you're interested in trying another similar issue, see #182, or let me know if you'd like to try something more challenging.

**Comment by utsavatwork** [comment]
> Thanks for the PR! You can now see the `IterableDoubleStream` at https://code-chronicles-code.github.io/leetcode-curriculum/ (The UI hasn't been a priority recently 😅)
> 
> If you're interested in trying another similar issue, see #182, or let me know if you'd like to try something more challenging.

Wow. Thanks @miorel. I just did my first open source contribution. I'd love to continue with this. I can start with #182 for now and then we might move to something more challenging for sure.

**Comment by miorel** [comment]
Congrats! 🎉

**Comment by volkmchl** [comment]
Congrats on your first contribution!

**Pull request merged**
