### PR TITLE
Add IterableLongStream java goodie in adventure-pack

### PR DESCRIPTION
**Pull request by utsavatwork**
Addresses the ticket #182

### CODE REVIEW

**Comment by utsavatwork** [comment]
@miorel please check this PR for the ticket #182

**Review by miorel — APPROVED** [review]
Looks good, thank you!

**Comment by miorel** [comment]
> I see the 3 out of 4 checks (PR health report) have failed. how do I address it?

I checked the logs -- everything is actually fine, it's failing when trying to post the report on the PR. I'm not totally sure why that is, it seems to be a permission issue. It'll be something to look into later.

**Comment by utsavatwork** [comment]
> > I see the 3 out of 4 checks (PR health report) have failed. how do I address it?
> 
> I checked the logs -- everything is actually fine, it's failing when trying to post the report on the PR. I'm not totally sure why that is, it seems to be a permission issue. It'll be something to look into later.

Ohkk. Cool!

**Comment by utsavatwork** [comment]
> > I see the 3 out of 4 checks (PR health report) have failed. how do I address it?
> 
> I checked the logs -- everything is actually fine, it's failing when trying to post the report on the PR. I'm not totally sure why that is, it seems to be a permission issue. It'll be something to look into later.

Ohkk. Cool!

**Comment by utsavatwork** [comment]
> > I see the 3 out of 4 checks (PR health report) have failed. how do I address it?
> 
> I checked the logs -- everything is actually fine, it's failing when trying to post the report on the PR. I'm not totally sure why that is, it seems to be a permission issue. It'll be something to look into later.

Ohkk. Cool!

**Comment by utsavatwork** [comment]
> > I see the 3 out of 4 checks (PR health report) have failed. how do I address it?
> 
> I checked the logs -- everything is actually fine, it's failing when trying to post the report on the PR. I'm not totally sure why that is, it seems to be a permission issue. It'll be something to look into later.

Ohkk. Cool!

**Comment by utsavatwork** [comment]
> > I see the 3 out of 4 checks (PR health report) have failed. how do I address it?
> 
> I checked the logs -- everything is actually fine, it's failing when trying to post the report on the PR. I'm not totally sure why that is, it seems to be a permission issue. It'll be something to look into later.

Ohkk. Cool!

**Comment by utsavatwork** [comment]
> > I see the 3 out of 4 checks (PR health report) have failed. how do I address it?
> 
> I checked the logs -- everything is actually fine, it's failing when trying to post the report on the PR. I'm not totally sure why that is, it seems to be a permission issue. It'll be something to look into later.

Ohkk. Cool!

**Comment by utsavatwork** [comment]
> > I see the 3 out of 4 checks (PR health report) have failed. how do I address it?
> 
> I checked the logs -- everything is actually fine, it's failing when trying to post the report on the PR. I'm not totally sure why that is, it seems to be a permission issue. It'll be something to look into later.

Ohkk. Cool!

**Pull request merged**
